version: '3'

services:
  task-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-habit-tracker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
